### ISSUE TITLE
PhpStan Error

### ISSUE THREAD

**Issue by ronappleton** [Stematic/testing#1]
Error:

ErrorException thrown in /home/ron/PhpstormProjects/laravel-sms/vendor/nunomaduro/larastan/src/ApplicationResolver.php on line 41 while loading bootstrap file /home/ron/PhpstormProjects/laravel-sms/vendor/nunomaduro/larastan/bootstrap.php: Undefined array key "psr-4"

@pdawson

PHP 8.1.3

Testing package

**Comment by pdawson** [comment]
Can't replicate this one.

Might be fine now with having the binary anyway.

**Comment by ronappleton** [comment]
Yup
